services:
  - type: web
    name: lyria-servicodetranscricao
    env: python
    region: frankfurt  
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: API_do_BACK
        value: "https://seu-back-end.onrender.com"  
    buildpacks:
      - https://github.com/render-examples/ffmpeg-buildpack.git
      - heroku/python